service: AWS-LAMBDA-API
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-west-1
  apiGateway:
    shouldStartNameWithService: true

plugins:
  - serverless-offline

functions:
  listPeople:
    handler: src/services/peopleServices.listPeople
    events:
      - http:
          path: /list
          method: get
  registerPeople:
    handler: src/services/peopleServices.registerPeople
    events:
      - http:
          path: /save/{id}
          method: post

resources:
  Resources:
    PeopleSwapiTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PeopleSwapiTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: createAt
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: createAt
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
